# Your Name or Company
title: 我爱利利

# Description of your website. This is used for social sharing.
description:  The beautiful website of artist, poet, craftsperson, cyclist, and avid juggler, Uni Kravitz.

# A brief blurb about yourself
content: 利利是我的恋人，也是我最好的朋友，她虽然总是傻乎乎的，但我真的很爱她，嘻嘻。这是一个记录我们生活中美好瞬间的网站，以后的人生中，愿我们能一起历经山河，觉得人间值得 

# Add your social links

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
